#!/bin/bash

# reference:
#   https://github.com/containerd/containerd/blob/main/docs/getting-started.md
#   https://blog.frognew.com/2023/12/kubeadm-install-kubernetes-1.29.html
#
install() {
  # prepare vars
  local name="$PACKAGE_CORE_NAME"

  log::info "[$(timestamp)][package][$name] preparing ..."

  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./bin/$name"

  case $platform in
  linux)
    case $arch in
    arm64 | amd64) ;;

    *)
      log::error "[$(timestamp)] $platform unsupport arch: $arch"
      return 1
      ;;
    esac
    ;;
  *)
    log::error "[$(timestamp)] unsupport platform: $platform"
    return 1
    ;;
  esac

  # prepare context
  cd $tmp_dir

  # reference: https://github.com/containerd/containerd/releases
  # example:
  #   https://github.com/containerd/containerd/releases/download/v1.6.15/containerd-1.6.15-linux-amd64.tar.gz
  #   https://github.com/containerd/containerd/releases/download/v1.6.15/containerd-1.6.15-linux-arm64.tar.gz
  # generate url
  local url="${PACKAGE_CORE_RELEASE_DOWNLOAD}/$PACKAGE_CORE_VERSION/${name}-${PACKAGE_CORE_VERSION#v}-${platform}-${arch}.tar.gz"
  log::debug "[$(timestamp)][package][$name][$kernel][$arch] url: $url, file: ${tmp_file}, tmp_dir: $tmp_dir"

  # download
  log::info "[$(timestamp)][package][$name] downloading ..."
  os::download $tmp_file $url

  # extract
  log::info "[$(timestamp)][package][$name] extracting ..."
  os::extract $tmp_file

  # install
  log::info "[$(timestamp)][package][$name] installing ..."
  # os::install $bin_file $usr_bin_dir
  # install ctr
  # os::install ./bin/ctr $usr_bin_dir
  # files: bin/{containerd,containerd-shim,containerd-shim-runc-v1,containerd-shim-runc-v2,containerd-stress,ctr}
  sudo mv ./bin/* $usr_bin_dir

  # @TODO add ln to /usr/local/bin for containerd.service
  sudo ln -sf /usr/bin/containerd /usr/local/bin/containerd

  # kernel modules
  #   reference: https://blog.frognew.com/2023/12/kubeadm-install-kubernetes-1.29.html
  if [ ! -f "/etc/modules-load.d/containerd.conf" ]; then
    cp $PACKAGE_DIR/conf/etc/modules-load.d/containerd.conf /etc/modules-load.d/containerd.conf
  fi
  log::info "[$(timestamp)][package][$name] loading kernel modules ..."
  sudo modprobe overlay
  sudo modprobe br_netfilter

  # kernel configs
  if [ ! -f "/etc/sysctl.d/99-kubernetes-cri.conf" ]; then
    cp $PACKAGE_DIR/conf/etc/sysctl.d/99-kubernetes-cri.conf /etc/sysctl.d/99-kubernetes-cri.conf
  fi
  log::info "[$(timestamp)][package][$name] apply kernel configs ..."
  sudo sysctl -p /etc/sysctl.d/99-kubernetes-cri.conf

  # @TODO config
  local containerd_config_dir="/etc/containerd"
  local containerd_config_file="$containerd_config_dir/config.toml"
  if [ ! -f "$containerd_config_file" ]; then
    sudo mkdir -p /etc/containerd
    # sudo containerd config default > $containerd_config_file
    sudo cp $PACKAGE_DIR/conf/config.toml $containerd_config_file
  fi

  if [ "$(os::has_command systemctl)" = "true" ]; then
    log::info "[$(timestamp)][package][$name] starting containerd service with systemd ..."
    local systemd_dir="/etc/systemd/system"
    if [ ! -d "${systemd_dir}" ]; then
      sudo mkdir -p ${systemd_dir}
    fi
    
    log::info "[$(timestamp)][package][$name] copying containerd.service to ${systemd_dir}/containerd.service ..."
    sudo cp $PACKAGE_DIR/conf/containerd.service ${systemd_dir}/containerd.service \
      && sudo systemctl daemon-reload \
      && sudo systemctl enable --now containerd
    if [ "$?" != "0" ]; then
      log::error "[$(timestamp)][package][$name] failed to start containerd service with systemd."
      return 1
    fi

    log::info "[$(timestamp)][package][$name] checking containerd service status ..."
    sudo systemctl status --no-pager containerd

    log::info "[$(timestamp)][package][$name] checking containerd version with ctr ..."
    sudo ctr --address /var/run/containerd/containerd.sock version

    log::success "[$(timestamp)][package][$name] succeed to start containerd service with systemd."
  fi

  # clean
  log::info "[$(timestamp)][package][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
