#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install ${PACKAGE_NAME} <args...>"
  echo ""
}

depends() {
  if [ "$(os::has_command runc)" != "true" ]; then
    zmicro package install runc
  fi

  # cni-plugins is required
  if [ ! -d "/opt/cni/bin" ]; then
    zmicro package install cni-plugins
  fi

  # nerdctl is required
  if [ "$(os::has_command nerdctl)" != "true" ]; then
    zmicro package install nerdctl
  fi
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  depends

  install
  if [ $? -eq 0 ]; then
    log::success "install ${PACKAGE_NAME} success."
    exit 0
  else
    log::error "install ${PACKAGE_NAME} failed."
    exit 1
  fi
}

run() {
  core "$@"
}

if [ "$1" = "ONE_LINE" ]; then
  command -v zmicro >>/dev/null 2>&1
  if [ $? -ne 0 ]; then
    curl -o- https://raw.githubusercontent.com/zcorky/zmicro/master/install | sh
  fi

  zmicro package install containerd
else
  set -e
  
  run "$@"
fi
